import type {
  PreviewPortalAsset,
  PreviewPortalIndexRenderOptions,
  PreviewPortalProject,
  PreviewPortalRenderOptions,
  PreviewPortalSurface,
  PreviewPortalTemplate,
} from './types.js';
import { PORTAL_CLIENT_JS, PORTAL_CSS, PORTAL_EDITOR_JS, PORTAL_JS } from './shared-assets.js';
import { resolvePreviewPortalTemplate } from './templates.js';

export function renderPreviewPortalHtml(options: PreviewPortalRenderOptions): string {
  if (options.surface === 'compare') {
    return renderComparePortalHtml(options);
  }
  const mode = modeForSurface(options.surface);
  const { project } = options;
  const template = resolvePreviewPortalTemplate(project.template);
  const final = project.assets.find((asset) => asset.section === 'final' && asset.kind === 'video');
  const stats = [
    [project.run.runId, 'run'],
    [template.name, 'template'],
    [String(project.assets.filter((asset) => asset.kind === 'video').length), 'videos'],
    [String(project.assets.filter((asset) => asset.kind === 'image').length), 'images'],
  ];
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="data:,">
<title>${esc(project.title)}</title>
<style>${PORTAL_CSS}</style>
</head>
<body data-mode="${mode}">
<nav class="toc" id="toc" aria-label="Sections"></nav>
<header class="hero">
  <div class="eyebrow">${labelForSurface(options.surface)} · ${esc(template.heroLabel)}</div>
  <h1>${esc(project.title)}</h1>
  ${project.summary ? `<p class="sub">${esc(project.summary)}</p>` : ''}
  <div class="stats">${stats.map(([value, label]) => `<div class="stat"><div class="v">${esc(value)}</div><div class="l">${esc(label)}</div></div>`).join('')}</div>
</header>
${final ? renderHeroVideo(final, template) : ''}
${renderTemplateSections(project, template, options.surface)}
${renderHud(options.surface)}
<footer>Generated by videoclaw · ${esc(project.slug)} · ${esc(project.run.updatedAt)}</footer>
<script>${PORTAL_JS}${scriptForSurface(options.surface)}</script>
</body>
</html>
`;
}

export function renderPreviewPortalIndexHtml(options: PreviewPortalIndexRenderOptions): string {
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const title = options.title ?? (options.client ? `${options.client} Review Index` : 'Videoclaw Review Index');
  const stats = [
    [String(options.projects.length), 'projects'],
    [String(options.projects.filter((project) => project.status === 'published').length), 'published'],
    [String(options.projects.filter((project) => project.status.includes('review')).length), 'in review'],
    [String(options.projects.reduce((sum, project) => sum + project.assets.length, 0)), 'assets'],
  ];
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="data:,">
<title>${esc(title)}</title>
<style>${PORTAL_CSS}</style>
</head>
<body data-mode="preview">
<nav class="toc" id="toc" aria-label="Sections"></nav>
<header class="hero">
  <div class="eyebrow">client portal · ${options.client ? esc(options.client) : 'all clients'}</div>
  <h1>${esc(title)}</h1>
  <p class="sub">Review, compare, and deliver generated video projects from one consistent index.</p>
  <div class="stats">${stats.map(([value, label]) => `<div class="stat"><div class="v">${esc(value)}</div><div class="l">${esc(label)}</div></div>`).join('')}</div>
</header>
<section id="projects" data-toc="Projects">
  <div class="section-head"><h2>Projects</h2><div class="section-title">Project Library</div><div class="section-sub">${options.projects.length} project${options.projects.length === 1 ? '' : 's'} available.</div></div>
  <div class="grid">
    ${options.projects.map((project) => renderProjectIndexCard(project, {
      linkPrefix: options.linkPrefix ?? '',
      linkMode: options.linkMode ?? 'local',
      client: options.client ?? null,
    })).join('') || '<div class="card"><div class="meta"><div class="title">No projects found</div><div class="who">Generate a project portal first, then rebuild this index.</div></div></div>'}
  </div>
</section>
<footer>Generated by videoclaw · ${esc(generatedAt)}</footer>
<script>${PORTAL_JS}</script>
</body>
</html>
`;
}

function renderComparePortalHtml(options: PreviewPortalRenderOptions): string {
  const projects = options.compareProjects?.length ? options.compareProjects : [options.project];
  const title = `${options.project.title} Compare`;
  const stats = [
    [String(projects.length), 'versions'],
    [String(projects.filter((project) => project.assets.some((asset) => asset.section === 'final' && asset.kind === 'video')).length), 'finals'],
    [String(projects.reduce((sum, project) => sum + project.assets.filter((asset) => asset.kind === 'video').length, 0)), 'videos'],
    [String(projects.reduce((sum, project) => sum + project.assets.filter((asset) => asset.kind === 'image').length, 0)), 'images'],
  ];
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="data:,">
<title>${esc(title)}</title>
<style>${PORTAL_CSS}</style>
</head>
<body data-mode="compare">
<nav class="toc" id="toc" aria-label="Sections"></nav>
<header class="hero">
  <div class="eyebrow">compare · ${esc(options.project.template)}</div>
  <h1>${esc(title)}</h1>
  ${options.project.summary ? `<p class="sub">${esc(options.project.summary)}</p>` : ''}
  <div class="stats">${stats.map(([value, label]) => `<div class="stat"><div class="v">${esc(value)}</div><div class="l">${esc(label)}</div></div>`).join('')}</div>
</header>
<section id="versions" data-toc="Versions">
  <div class="section-head"><h2>Versions</h2><div class="section-title">Run Comparison</div><div class="section-sub">Compare finals, run metadata, and links for each generated version.</div></div>
  <div class="grid">
    ${projects.map((project) => renderCompareCard(options.project.projectDir, project)).join('')}
  </div>
</section>
<footer>Generated by videoclaw · ${esc(options.project.slug)} · ${esc(options.project.run.updatedAt)}</footer>
<script>${PORTAL_JS}</script>
</body>
</html>
`;
}

function renderHeroVideo(asset: PreviewPortalAsset, template: PreviewPortalTemplate): string {
  return `<div class="hero-video">
  <video controls preload="metadata" playsinline data-downloadable src="${escAttr(asset.path)}"></video>
  <div class="final-meta"><span class="num">${esc(template.primaryAssetLabel)}</span><span>${esc(asset.path)}</span></div>
</div>`;
}

function renderProjectIndexCard(
  project: PreviewPortalProject,
  options: { linkPrefix: string; linkMode: 'local' | 'published-run'; client?: string | null },
): string {
  const final = project.assets.find((asset) => asset.section === 'final' && asset.kind === 'video');
  const poster = project.assets.find((asset) => asset.kind === 'image');
  const base = projectIndexBase(project, options);
  const media = final
    ? `<video controls preload="metadata" data-downloadable src="${escAttr(base)}/${escAttr(final.path)}"></video>`
    : poster
      ? `<img data-downloadable data-lightbox-group="projects" data-lb-caption="${escAttr(project.title)}" src="${escAttr(base)}/${escAttr(poster.path)}" alt="${escAttr(project.title)}">`
      : '';
  return `<div class="card" data-card-kind="project" data-card-id="${escAttr(project.slug)}">
    ${media}
    <div class="meta"><div class="num">${esc(project.status)}</div><div class="title">${esc(project.title)}</div><div class="who">${esc(project.slug)} · ${esc(project.template)} · ${esc(project.run.updatedAt)}</div>
      <div class="who"><a href="${escAttr(base)}/preview.html">Preview</a> · <a href="${escAttr(base)}/client-review.html">Client Review</a> · <a href="${escAttr(base)}/edit.html">Edit Review</a> · <a href="${escAttr(base)}/review.html">Editor Review</a> · <a href="${escAttr(base)}/compare.html">Compare</a></div>
    </div>
  </div>`;
}

function projectIndexBase(
  project: PreviewPortalProject,
  options: { linkPrefix: string; linkMode: 'local' | 'published-run'; client?: string | null },
): string {
  if (options.linkMode === 'local') return `${options.linkPrefix}${project.slug}`;
  const runPath = `${project.slug}/runs/${project.run.runId}`;
  if (options.client) return `${options.linkPrefix}${runPath}`;
  return `${options.linkPrefix}clients/${slugify(project.client ?? 'unknown')}/${runPath}`;
}

function renderCompareCard(baseProjectDir: string, project: PreviewPortalProject): string {
  const final = project.assets.find((asset) => asset.section === 'final' && asset.kind === 'video');
  const prefix = relativePrefix(baseProjectDir, project.projectDir);
  const media = final
    ? `<video controls preload="metadata" data-downloadable src="${escAttr(prefix)}${escAttr(final.path)}"></video>`
    : '<div class="meta"><code>No final video discovered</code></div>';
  return `<div class="card" data-card-kind="run" data-card-id="${escAttr(project.slug)}-${escAttr(project.run.runId)}">
    ${media}
    <div class="meta"><div class="num">${esc(project.run.status)}</div><div class="title">${esc(project.title)}</div><div class="who">${esc(project.slug)} · ${esc(project.run.runId)} · ${esc(project.template)}</div>
      <div class="who">Updated ${esc(project.run.updatedAt)}</div>
      <div class="who"><a href="${escAttr(prefix)}preview.html">Preview</a> · <a href="${escAttr(prefix)}client-review.html">Client Review</a> · <a href="${escAttr(prefix)}review.html">Editor Review</a></div>
    </div>
  </div>`;
}

function relativePrefix(baseProjectDir: string, targetProjectDir: string): string {
  if (baseProjectDir === targetProjectDir) return '';
  const base = baseProjectDir.split('/').filter(Boolean);
  const target = targetProjectDir.split('/').filter(Boolean);
  while (base.length && target.length && base[0] === target[0]) {
    base.shift();
    target.shift();
  }
  return `${base.map(() => '..').join('/')}/${target.join('/')}/`.replace(/^\//, '');
}

function renderCardsSection(
  id: string,
  title: string,
  assets: PreviewPortalAsset[],
  surface: PreviewPortalSurface,
): string {
  if (assets.length === 0) return '';
  return `<section id="${id}" data-toc="${escAttr(title)}">
  <div class="section-head"><h2>${esc(title)}</h2><div class="section-title">${esc(title)}</div><div class="section-sub">${assets.length} item${assets.length === 1 ? '' : 's'} discovered.</div></div>
  <div class="grid">
    ${assets.map((asset) => renderAssetCard(asset, surface)).join('')}
  </div>
</section>`;
}

function renderTemplateSections(
  project: PreviewPortalProject,
  template: PreviewPortalTemplate,
  surface: PreviewPortalSurface,
): string {
  return template.sectionOrder
    .map((section) => {
      const assets = project.assets.filter((asset) => asset.section === section);
      return renderCardsSection(sectionId(section), template.sectionLabels[section] ?? titleFromSection(section), assets, surface);
    })
    .join('');
}

function sectionId(section: string): string {
  if (section === 'final') return 'finals';
  return section.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
}

function titleFromSection(section: string): string {
  return section
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join(' ');
}

function renderAssetCard(asset: PreviewPortalAsset, surface: PreviewPortalSurface): string {
  const kind = asset.section === 'final' ? 'final' : asset.section === 'videos' ? 'scene' : 'asset';
  const media = asset.kind === 'video'
    ? `<video controls preload="metadata" data-downloadable src="${escAttr(asset.path)}"></video>`
    : asset.kind === 'image'
      ? `<img data-downloadable data-lightbox-group="${escAttr(asset.section)}" data-lb-caption="${escAttr(asset.label)}" src="${escAttr(asset.path)}" alt="${escAttr(asset.label)}">`
      : asset.kind === 'audio'
        ? `<div class="meta"><audio controls data-downloadable src="${escAttr(asset.path)}"></audio></div>`
        : `<div class="meta"><code>${esc(asset.path)}</code></div>`;
  return `<div class="card" data-card-kind="${kind}" data-card-id="${escAttr(asset.id)}">
    ${media}
    <div class="meta"><div class="num">${esc(asset.section)}</div><div class="title">${esc(asset.label)}</div><div class="who">${esc(asset.path)}</div></div>
    ${renderControls(surface)}
  </div>`;
}

function renderControls(surface: PreviewPortalSurface): string {
  if (surface === 'edit' || surface === 'review') {
    return `<div class="review-controls">
      <button type="button" class="review-btn approve" data-review-action="approve" aria-pressed="false">Approve</button>
      <button type="button" class="review-btn regenerate" data-review-action="regenerate" aria-pressed="false">Regenerate</button>
      <input type="text" class="review-note" placeholder="why / what to change">
    </div>`;
  }
  if (surface === 'client-review') {
    return `<div class="client-controls">
      <button type="button" class="client-btn approve" data-client-action="approve" aria-pressed="false">Approve</button>
      <button type="button" class="client-btn decline" data-client-action="decline" aria-pressed="false">Decline</button>
      <input type="text" class="client-note" placeholder="comment">
    </div>`;
  }
  return '';
}

function renderHud(surface: PreviewPortalSurface): string {
  if (surface === 'edit' || surface === 'review') {
    return `<div class="hud" id="review-hud" role="status"><span id="rs-approved">0 approved</span><span id="rs-regen">0 to regenerate</span><button type="button" id="copy-decisions-btn">Copy Review Decisions</button></div>`;
  }
  if (surface === 'client-review') {
    return `<div class="hud" id="client-hud" role="status"><span>Client feedback</span><button type="button" id="copy-client-feedback-btn">Copy Feedback</button></div>`;
  }
  return '';
}

function modeForSurface(surface: PreviewPortalSurface): 'editor' | 'client' | 'preview' | 'compare' {
  if (surface === 'edit' || surface === 'review') return 'editor';
  if (surface === 'client-review') return 'client';
  if (surface === 'compare') return 'compare';
  return 'preview';
}

function labelForSurface(surface: PreviewPortalSurface): string {
  if (surface === 'edit') return 'editor edit';
  if (surface === 'review') return 'editor review';
  if (surface === 'client-review') return 'client review';
  if (surface === 'compare') return 'compare';
  if (surface === 'index') return 'index';
  return 'preview';
}

function scriptForSurface(surface: PreviewPortalSurface): string {
  if (surface === 'edit' || surface === 'review') return PORTAL_EDITOR_JS;
  if (surface === 'client-review') return PORTAL_CLIENT_JS;
  return '';
}

function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'unknown';
}

function esc(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escAttr(value: string): string {
  return esc(value);
}
