import type { StudioRecipe } from './types.js';

export const STUDIO_RECIPES: StudioRecipe[] = [
  {
    id: 'create-video',
    title: 'Create New Video',
    goal: 'Create an original video from a brief, references, or scratch concept.',
    useWhen: ['product ad', 'brand film', 'short film', 'explainer', 'new video'],
    requiredInputs: ['project', 'intent'],
    optionalInputs: ['title', 'durationSeconds', 'client'],
    riskLevel: 'medium',
    executionPolicy: 'dry-run-first',
    commands: [
      {
        id: 'create-dry-run',
        title: 'Draft production plan',
        primary: 'vclaw video create <intent> --project <project> --dry-run',
        when: 'always',
        produces: ['brief.json', 'storyboard.json', 'execution profile preview'],
      },
      {
        id: 'readiness',
        title: 'Check project readiness',
        primary: 'vclaw video readiness --project <project>',
        when: 'after brief and storyboard exist',
        produces: ['readiness.json'],
      },
    ],
  },
  {
    id: 'copy-reference',
    title: 'Copy Or Adapt Reference',
    goal: 'Analyze a reference video or ad and adapt it for a new subject.',
    useWhen: ['copy ad', 'clone reel', 'reference video', 'replicate'],
    requiredInputs: ['project', 'input', 'intent'],
    optionalInputs: ['client'],
    riskLevel: 'medium',
    executionPolicy: 'plan-first',
    commands: [
      {
        id: 'analyze-reference',
        title: 'Analyze source reference',
        primary: 'vclaw video analyze --project <project> --source <input> --auto',
        when: 'reference source is available',
        produces: ['analyze-output.json'],
      },
      {
        id: 'clone-plan',
        title: 'Build clone plan',
        primary: 'vclaw video clone-plan --template <template> --project <project> --intent <intent>',
        when: 'analysis has produced or selected a template',
        produces: ['clone-plan.json'],
      },
    ],
  },
  {
    id: 'presenter-video',
    title: 'Presenter Video',
    goal: 'Create a Bunty, Nex, Davendra, or generic presenter episode from a deck or brief.',
    useWhen: ['Bunty', 'Nex', 'Davendra', 'presenter', 'slides', 'deck'],
    requiredInputs: ['project', 'input'],
    optionalInputs: ['client', 'title', 'intent'],
    riskLevel: 'medium',
    executionPolicy: 'approval-gated',
    commands: [
      {
        id: 'assemble-dry-run',
        title: 'Plan presenter assembly',
        primary: 'vclaw video assemble --project <project> --dry-run',
        when: 'slides or project assets exist',
        produces: ['assemble-report.json'],
      },
      {
        id: 'portal',
        title: 'Create review portal',
        primary: 'vclaw video portal --project <project> --client <client> --surface review',
        when: 'reviewable media exists',
        produces: ['preview portal HTML'],
      },
    ],
  },
  {
    id: 'music-video',
    title: 'Music Video And Multi-Shot',
    goal: 'Plan a music-video or cinematic sequence using prompt packets, storyboard grids, and multi-shot prompts.',
    useWhen: ['music video', 'multi-shot', 'cinematic sequence', 'Seedance'],
    requiredInputs: ['project'],
    optionalInputs: ['durationSeconds', 'intent', 'input'],
    riskLevel: 'high',
    executionPolicy: 'approval-gated',
    commands: [
      {
        id: 'filmmaking-prompts',
        title: 'Generate filmmaking prompt packet',
        primary: 'vclaw video filmmaking-prompts --project <project> --duration <durationSeconds> --storyboard-grid artifacts/storyboard-grid.png --write',
        when: 'storyboard exists or a project concept exists',
        produces: ['filmmaking-prompts.json', 'storyboard-grid.png'],
      },
      {
        id: 'multi-shot',
        title: 'Create multi-shot prompt',
        primary: 'vclaw video multi-shot --from-storyboard --project <project> --scene 0 --preset cinematic-15s',
        when: 'storyboard scene exists',
        produces: ['multi-shot-prompt.json'],
      },
      {
        id: 'readiness',
        title: 'Check project readiness',
        primary: 'vclaw video readiness --project <project>',
        when: 'after prompt packet and storyboard assets exist',
        produces: ['readiness.json'],
      },
      {
        id: 'execute-dry-run',
        title: 'Preview provider execution',
        primary: 'vclaw video execute --project <project> --dry-run',
        when: 'readiness is green or warnings are accepted',
        produces: ['execution-report.json'],
      },
      {
        id: 'review-portal',
        title: 'Create review surface',
        primary: 'vclaw video portal --project <project> --surface review',
        when: 'after clips or storyboard media exist',
        produces: ['review portal HTML'],
      },
    ],
  },
  {
    id: 'ugc-campaign',
    title: 'UGC Campaign',
    goal: 'Plan a belief-driven campaign with hooks, scripts, variants, and assembly.',
    useWhen: ['UGC', 'testimonial', 'campaign', 'creator ad'],
    requiredInputs: ['project', 'intent'],
    optionalInputs: ['input', 'client'],
    riskLevel: 'medium',
    executionPolicy: 'plan-first',
    commands: [
      {
        id: 'ugc-brief',
        title: 'Create UGC brief',
        primary: 'vclaw video create <intent> --project <project> --production-mode director --platform tiktok --dry-run',
        when: 'campaign idea is known',
        produces: ['brief.json', 'storyboard.md'],
      },
      {
        id: 'review-ui',
        title: 'Plan UGC review surface',
        primary: 'vclaw video review-ui --project <project> --dry-run',
        when: 'draft scenes or candidates exist',
        produces: ['review-ui plan'],
      },
    ],
  },
  {
    id: 'existing-project',
    title: 'Continue Existing Project',
    goal: 'Inspect a project and recommend the next action based on artifacts and readiness.',
    useWhen: ['continue', 'status', 'what next', 'existing project'],
    requiredInputs: ['project'],
    optionalInputs: ['client'],
    riskLevel: 'low',
    executionPolicy: 'dry-run-first',
    commands: [
      {
        id: 'status',
        title: 'Read project status',
        primary: 'vclaw video status --project <project>',
        when: 'project exists',
        produces: ['status report'],
      },
      {
        id: 'readiness',
        title: 'Check readiness',
        primary: 'vclaw video readiness --project <project>',
        when: 'project exists',
        produces: ['readiness.json'],
      },
      {
        id: 'next-actions',
        title: 'Recommend next actions',
        primary: 'vclaw video next-actions',
        when: 'project exists',
        produces: ['portfolio next actions'],
      },
    ],
  },
  {
    id: 'review-regenerate',
    title: 'Review Or Regenerate',
    goal: 'Review generated scenes, select candidates, reroll weak scenes, and prepare approval.',
    useWhen: ['review', 'regenerate', 'reroll', 'fix scene', 'approve'],
    requiredInputs: ['project'],
    optionalInputs: ['client'],
    riskLevel: 'medium',
    executionPolicy: 'approval-gated',
    commands: [
      {
        id: 'review-ui',
        title: 'Open review UI',
        primary: 'vclaw video review-ui --project <project> --dry-run',
        when: 'project has reviewable artifacts',
        produces: ['review-ui plan'],
      },
      {
        id: 'candidates-list',
        title: 'List scene candidates',
        primary: 'vclaw video candidates-list --project <project>',
        when: 'scene candidates exist',
        produces: ['candidate summary'],
      },
    ],
  },
  {
    id: 'publish-deliver',
    title: 'Publish And Deliver',
    goal: 'Package final media and publish a client review or delivery portal.',
    useWhen: ['publish', 'client portal', 'deliver', 'share'],
    requiredInputs: ['project', 'client'],
    optionalInputs: ['input'],
    riskLevel: 'medium',
    executionPolicy: 'approval-gated',
    commands: [
      {
        id: 'portal',
        title: 'Build portal',
        primary: 'vclaw video portal --project <project> --client <client> --surface client-review',
        when: 'reviewable project exists',
        produces: ['client review portal'],
      },
      {
        id: 'publish-preview-dry-run',
        title: 'Plan portal publishing',
        primary: 'vclaw video publish-preview --project <project> --client <client> --bucket <bucket> --dry-run',
        when: 'bucket is known',
        produces: ['publish plan'],
      },
    ],
  },
];

export function findStudioRecipe(id: string): StudioRecipe | undefined {
  return STUDIO_RECIPES.find((recipe) => recipe.id === id);
}
